services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: fly_elysia_react
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-queue
    command: redis-server --requirepass ${REDIS_PASSWORD:-dev-redis-password-change-in-production}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-dev-redis-password-change-in-production}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-dev-redis-password-change-in-production}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fly_elysia_react
      - BETTER_AUTH_SECRET=dev-secret-key-change-in-production
      - BETTER_AUTH_URL=http://localhost:3001
      - REDIS_URL=redis://:${REDIS_PASSWORD:-dev-redis-password-change-in-production}@redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./apps/server/src:/app/apps/server/src:cached
      - ./apps/server/package.json:/app/apps/server/package.json:cached
      - ./apps/server/tsconfig.json:/app/apps/server/tsconfig.json:cached
      - ./apps/server/drizzle.config.ts:/app/apps/server/drizzle.config.ts:cached
      - ./apps/server/drizzle:/app/apps/server/drizzle:cached
      - ./packages/shared:/app/packages/shared:cached
      - /app/node_modules
      - /app/apps/server/node_modules

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./apps/client/src:/app/apps/client/src:cached
      - ./apps/client/public:/app/apps/client/public:cached
      - ./apps/client/index.html:/app/apps/client/index.html:cached
      - ./packages/shared:/app/packages/shared:cached
      - /app/node_modules
      - /app/apps/client/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
