# Docker Compose for Local Development
# This configuration includes hot reloading and development settings

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-your_database_name}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for Job Queue
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-dev-redis-password-change-in-production}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-dev-redis-password-change-in-production}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-dev-redis-password-change-in-production}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend Server (Development with hot reload)
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-your_database_name}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-dev-secret-key-change-in-production}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3001}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-dev-redis-password-change-in-production}@redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RUN_WORKERS=${RUN_WORKERS:-true}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      # Mount source code for hot reloading
      - ./apps/server/src:/app/apps/server/src:cached
      - ./apps/server/package.json:/app/apps/server/package.json:cached
      - ./apps/server/tsconfig.json:/app/apps/server/tsconfig.json:cached
      - ./apps/server/drizzle.config.ts:/app/apps/server/drizzle.config.ts:cached
      - ./apps/server/drizzle:/app/apps/server/drizzle:cached
      - ./packages/shared:/app/packages/shared:cached
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/apps/server/node_modules

  # Frontend Client (Development with hot reload)
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      # Mount source code for hot reloading
      - ./apps/client/src:/app/apps/client/src:cached
      - ./apps/client/public:/app/apps/client/public:cached
      - ./apps/client/index.html:/app/apps/client/index.html:cached
      - ./packages/shared:/app/packages/shared:cached
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/apps/client/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge