# fly.toml app configuration file for server
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "YOUR-APP-NAME-server"
primary_region = 'sea'

[build]
  dockerfile = "apps/server/Dockerfile"

[env]
  NODE_ENV = "production"

# Define multiple processes
[processes]
  web = "bun run start"
  worker = "bun run worker"

# HTTP service configuration for web process only
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]  # Only web process handles HTTP

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"

# VM configuration applies to all processes
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "immediate"

[experimental]
  auto_rollback = false