# fly.toml app configuration file for bun-app-server
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bun-app-server'
primary_region = 'sea'

[build]
  dockerfile = "apps/server/Dockerfile"

[env]
  NODE_ENV = "production"

# Define multiple processes
[processes]
  web = "bun run start"
  worker = "bun run worker"

# HTTP service configuration for web process
[[services]]
  processes = ["web"]
  internal_port = 3001
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"

# VM configuration
[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1